name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write   # for release
      packages: write   # for publishing docker images
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build binaries
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          mv target/x86_64-unknown-linux-musl/release/takis takis-linux-amd64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release ${{ github.ref_name }}'
          tag_name: ${{ github.ref_name }}
          files: |
            takis-linux-amd64
          generate_release_notes: true
          draft: ${{ contains(github.ref_name, 'rc') }}
          prerelease: ${{ contains(github.ref_name, 'rc') }}
